export const ROOT_PATH = '/'
export const USER_SIGN_IN_PATH = '/sign-in'
export const USER_SIGN_UP_PATH = '/sign-up'
export const ADD_BUSINESS_PATH = '/add-business'
export const BUSINESSES_INDEX_PATH = '/businesses'
