const dummyCompanies = [
  {
    name: "Codaisseur",
    address: "Singel 542, 1017 AZ Amsterdam",
    lattitude: 52.3666451,
    longitude: 4.8923966,
    companyType: "Education",
    industryType: "IT",
    hiring: true,
    website: "https://www.codaisseur.com/",
    email: "codaisseur@email.com",
    active: true,
  },
  {
    name: "CodeGuild",
    address: "Herengracht 174, 1016 BR Amsterdam",
    lattitude: 52.3739959,
    longitude: 4.886718,
    companyType: "HR",
    industryType: "IT",
    hiring: false,
    website: "https://www.codeguild.nl/",
    email: "CodeGuild@email.com",
    active: true,
  },
  {
    name: "Impraise",
    address: "Frederiksplein 1, 1017 XK Amsterdam",
    lattitude: 52.3612379,
    longitude: 4.899203,
    companyType: "HR",
    industryType: "IT",
    hiring: true,
    website: "https://www.impraise.com/",
    email: "Impraise@email.com",
    active: false,
  },
  {
    name: "Guerrilla",
    address: "Herengracht 601, 1017 CE Amsterdam",
    lattitude: 52.3655782,
    longitude: 4.8986419,
    companyType: "HR",
    industryType: "IT",
    hiring: false,
    website: "https://www.impraise.com/",
    email: "Guerrilla@email.com",
    active: false,
  },
]

export default dummyCompanies
